### ISSUE TITLE
Flask fails to load homepage, cannot find index.html

### ISSUE THREAD

**Issue by Fleker** [adeshpande3/Chatbot-Flask-Server#2]
I found this error when trying to deploy this project directly to Heroku:

```
 Traceback (most recent call last):
2018-02-23T07:44:29.364536+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
2018-02-23T07:44:29.364537+00:00 app[web.1]:     response = self.full_dispatch_request()
2018-02-23T07:44:29.364539+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
2018-02-23T07:44:29.364541+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2018-02-23T07:44:29.364543+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
2018-02-23T07:44:29.364544+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2018-02-23T07:44:29.364546+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
2018-02-23T07:44:29.364548+00:00 app[web.1]:     rv = self.dispatch_request()
2018-02-23T07:44:29.364549+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
2018-02-23T07:44:29.364551+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2018-02-23T07:44:29.364553+00:00 app[web.1]:   File "/app/app.py", line 64, in main
2018-02-23T07:44:29.364554+00:00 app[web.1]:     return render_template('index.html')
2018-02-23T07:44:29.364556+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
2018-02-23T07:44:29.364558+00:00 app[web.1]:     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
2018-02-23T07:44:29.364560+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
2018-02-23T07:44:29.364562+00:00 app[web.1]:     return self.get_template(template_name_or_list, parent, globals)
2018-02-23T07:44:29.364564+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
2018-02-23T07:44:29.364565+00:00 app[web.1]:     return self._load_template(name, self.make_globals(globals))
2018-02-23T07:44:29.364567+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
2018-02-23T07:44:29.364569+00:00 app[web.1]:     template = self.loader.load(self, name, globals)
2018-02-23T07:44:29.364570+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
2018-02-23T07:44:29.364572+00:00 app[web.1]:     source, filename, uptodate = self.get_source(environment, name)
2018-02-23T07:44:29.364573+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
2018-02-23T07:44:29.364575+00:00 app[web.1]:     return self._get_source_fast(environment, template)
2018-02-23T07:44:29.364577+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
2018-02-23T07:44:29.364578+00:00 app[web.1]:     raise TemplateNotFound(template)
2018-02-23T07:44:29.364580+00:00 app[web.1]: TemplateNotFound: index.html
```

The reason is that Flask is looking in [a non-existent subdirectory](https://stackoverflow.com/questions/33396064/flask-template-not-found) for the files. However, this can be easily fixed by updating our templates folder in `app.py`:

`app = Flask(__name__, template_folder='./')`

**Comment by adeshpande3** [comment]
Ah I see, sorry, I'm not as well versed in Flask, but yeah that makes sense. Thank you for pointing that out.
